// File: and_g.v
// Generated by MyHDL 1.0dev
// Date: Fri Jun 16 11:14:09 2017


`timescale 1ns/10ps

module and_g (
    a,
    b,
    c
);


input a;
input b;
output c;
wire c;





assign c = (a & b);

endmodule
